kelsey/customwp/models.py
from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)
import random
from colsan.models import Constants as colsanConstants
# from settings import SESSION_CONFIGS


doc = """
...testing timer on waiting page
"""


class Constants(BaseConstants):
    name_in_url = 'customwp'
    players_per_group = colsanConstants.players_per_group
    num_rounds = 1
    # the startwp_timer defines how long the player has to wait at the
    # first waiting page
    # before he or she has an option to finish the game without waiting for
    # others
    startwp_timer = 10


class Subsession(BaseSubsession):
    not_enough_players = models.BooleanField(
        doc=""" this variable set to True when one of the players decide to
        abandon the game (because he is tired to wait), and
        there is no enough players left in the session to complete the group.
        then those remaining get the opportunity to finish the game.""",
        initial=False
    )


class Group(BaseGroup):
    ...


class Player(BasePlayer):
    startwp_timer_set = models.BooleanField(default=False)
    startwp_time = models.PositiveIntegerField()
    outofthegame = models.BooleanField()

kelsey/models.py
from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)
import random
from math import ceil
from itertools import product
import csv
from collections import OrderedDict
from django import forms as djforms

author = 'Philipp Chapkovski, UZH'

doc = """
Kelsey-Oliva lottery game
"""


class Constants(BaseConstants):
    name_in_url = 'kelsey'
    players_per_group = None
    num_rounds = 18
    # till what round we play T0 and then change to whatever treatment
    # we have?::
    first_half = 9
    second_half = first_half + 1
    assert first_half <= num_rounds, "SOMETHING WRONG WITH NUMBER OF ROUNDS!"
    p = 0.7  # probability of low payoff
    initial_cost = 9
    final_cost = 15
    first_decision_labels = {
        'T0': """Do you want to pay an initial investment cost of ${}  with the final
    investment cost determined based on what value payoff
    is drawn?""".format(initial_cost),
        'T1': """Do you want to pay an initial investment cost of ${} to
    take this contract?""".format(initial_cost),
        'T2': """Do you want to pay an initial investment cost of ${} and a final investment
     cost of ${} to release the randomly determined payoff?""".format(initial_cost, final_cost),
    }
    low_payoff_set = [0, 6, 12]
    high_payoff_set = [24, 36, 54]
    payoffs_sets = list(product(low_payoff_set, high_payoff_set))
    # values for control questions:
    q_parameters = {'initial_cost': 9,
                    'final_cost': 15,
                    'high_payoff': 40,
                    'low_payoff': 8,
                    'PT0ExampleHigh': 16,
                    'PT0ExampleLow': -16,
                    }
    with open('kelsey/qs_to_add.csv') as f:
        questions = list(csv.DictReader(f))
    for q in questions:
        q['verbose'] = q['verbose'].format(
            initial=q_parameters['initial_cost'],
            final=q_parameters['final_cost'],
            hpayoff=q_parameters['high_payoff'],
            lpayoff=q_parameters['low_payoff'],
        )
        # a = dict(questions)
        # questions = OrderedDict(sorted(questions.items(), key=lambda item: item['number']))


def weighted_choice(a, b):
    assert 0 <= Constants.p <= 1, 'SOMETHING WRONG WITH PROBABILITIES, DUDE'
    selector = random.random()
    if selector <= Constants.p:
        return a
    return b


class Subsession(BaseSubsession):
    def before_session_starts(self):

        first_half = self.session.config.get('first_half', 'T0')
        second_half = self.session.config.get('second_half', 'T0')
        for p in self.get_players():
            curpayoffset = (Constants.payoffs_sets.copy())
            random.shuffle(curpayoffset)
            p.participant.vars.setdefault('payoffsets', curpayoffset)
            i = p.round_number % Constants.first_half - 1
            p.low_payoff = p.participant.vars['payoffsets'][i][0]
            p.high_payoff = p.participant.vars['payoffsets'][i][1]
            p.investment_payoff = weighted_choice(p.low_payoff, p.high_payoff)
            if p.round_number <= Constants.first_half:
                p.treatment = first_half
            else:
                p.treatment = second_half
                # print('######', len(Player.objects.filter(subsession=self)))
                # for p in self.get_players():
                #     p.treatment='yyyy'
                # import otree.db.idmap
                # # otree.db.idmap.save_objects()
                # otree.db.idmap.flush_cache()
                # Player.objects.filter(subsession=self).update(treatment='ыыыы')


class Group(BaseGroup):
    pass


class Player(BasePlayer):
    consent = models.BooleanField(widget=djforms.CheckboxInput,
                                  initial=False
                                  )
    treatment = models.CharField()
    investment_payoff = models.IntegerField()
    low_payoff = models.IntegerField()
    high_payoff = models.IntegerField()
    first_decision = models.BooleanField()
    second_decision = models.BooleanField(
        verbose_name="""Do you want to pay the final
        investment cost of ${} to
         release this payoff?""".format(Constants.final_cost)
    )
    # set of control questions for each treatment

    for i in Constants.questions:
        locals()[i['qname']] = models.CharField(verbose_name=i['verbose'],
                                                widget=widgets.RadioSelectHorizontal(),
                                                choices=[i['option1'], i['option2']])

    # filtered_dict = {k:v for (k,v) in d.items() if filter_string in k}

    #  END OF set of control questions for each treatment

    def set_payoffs(self):
        if self.treatment == 'T0':
            self.payoff = self.first_decision * \
                          (-Constants.initial_cost +
                           max(self.investment_payoff - Constants.final_cost, 0))
        if self.treatment == 'T1':
            self.payoff = self.first_decision * \
                          (-Constants.initial_cost +
                           (self.investment_payoff - Constants.final_cost) *
                           (self.second_decision or 0))
        if self.treatment == 'T2':
            self.payoff = self.first_decision * \
                          (-Constants.initial_cost +
                           self.investment_payoff - Constants.final_cost)


            # block of survey questions:

    gender = models.CharField(verbose_name='Gender', choices=['Male', 'Female', 'Other'],
                              widget=widgets.RadioSelectHorizontal, )
    nationality = models.CharField(verbose_name='Nationality', choices=['US', 'Other'],
                                   widget=widgets.RadioSelectHorizontal, )
    nationality_other = models.CharField(verbose_name='', blank=True)
    race_ethnicity = models.CharField(verbose_name='Race/Ethnicity',
                                      choices=['African American/African/Black/Caribbean',
                                               'Asian/Pacific Islander',
                                               'Caucasian',
                                               'Hispanic/Latino',
                                               'Native American',
                                               'Other',
                                               'Prefer not to answer '
                                               ],
                                      widget=widgets.RadioSelect, )
    race_ethnicity_other = models.CharField(verbose_name='', blank=True)
    major = models.CharField(verbose_name='Major', blank=True)
    year_in_college = models.CharField(verbose_name='Year in College', choices=[
        'Freshman/First-Year ',
        'Sophomore',
        'Junior',
        'Senior',
        'Graduate Student',
        'Other'
    ],
                                       blank=True)
    year_in_college_other = models.CharField(verbose_name='', )

    stock_market_experience = models.CharField(verbose_name='Do you have any experience with the stock market?',
                                               widget=widgets.RadioSelectHorizontal,
                                               choices=['Yes', 'No'])

    stock_market_explain = models.CharField(verbose_name='', )

    instructions = models.CharField(verbose_name='Were the instructions clear?',
                                    choices=['Yes', 'No'],
                                    widget=widgets.RadioSelect, )
    recommendations = models.CharField(verbose_name='Do you have any recommendations for improvements?',
                                       blank=True)

    CONFIDENT_CHOICES = ['Very Confident',
                         'Confident',
                         'Somewhat Unconfident',
                         'Unconfident',
                         ]

    random_contract = models.CharField(
        verbose_name='How confident were you that the experimenters truly randomized the payoff of each contract based on the stated probabilities?',
        choices=CONFIDENT_CHOICES,
        widget=widgets.RadioSelectHorizontal, )

    random_round = models.CharField(
        verbose_name='How confident were you that the experimenters truly chose the rounds for payments randomly?',
        choices=CONFIDENT_CHOICES,
        widget=widgets.RadioSelectHorizontal, )
    easiest = models.CharField(verbose_name='Which Part of the experiment did you find was easiest to think through?',
                               choices=['Part 1', 'Part 2'],
                               widget=widgets.RadioSelectHorizontal, )

    end_beginning = models.CharField(
        verbose_name='Do you think you made better decisions at the end of each Part or at the beginning of each Part?',
        choices=['Beginning', 'End'],
        widget=widgets.RadioSelectHorizontal, )
    pleasant = models.CharField(
        verbose_name='Would you say that you found being in this study a pleasant or unpleasant experience?',
        choices=['Extremely Pleasant',
                 'Pleasant',
                 'Somewhat Pleasant',
                 'Neither',
                 'Somewhat Unpleasant',
                 'Unpleasant',
                 'Extremely Unpleasant', ],
        widget=widgets.RadioSelectHorizontal, )

    thinking = models.CharField(
        verbose_name="""Please try to describe what you were thinking when you were making decisions 
        during the study.  What factors entered your decisions? And why did you make the choices you did?""",
        blank=True)

kelsey/forms.py
from django import forms
from . import models


class ConsentForm(forms.Form):
    def __init__(self, instance, view, *args, **kwargs):
        super(ConsentForm, self).__init__(*args, **kwargs)
    # class Meta:
    #     model = models.Player
    #     fields = ['consent']
    #     widgets = {
    #         'consent': forms.CheckboxInput(required=True),
    #     }

    consent = forms.BooleanField(required = True)
    # your other form fields

kelsey/_builtin/__init__.py
# This file is auto-generated.
# It's used to aid autocompletion in code editors.

import otree.api
from .. import models


class Page(otree.api.Page):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()


class WaitPage(otree.api.WaitPage):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()


class Bot(otree.api.Bot):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()

kelsey/customwp/_builtin/__init__.py
# Don't change anything in this file.
from .. import models
import otree.api

import otree.api
from otree.api import Currency as c, currency_range

class Page(otree.api.Page):

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()


class WaitPage(otree.api.WaitPage):


    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()


class Bot(otree.api.Bot):

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()

kelsey/customwp/views.py
from . import models
from ._builtin import Page, WaitPage
from otree.api import Currency as c, currency_range
# from otree.api import models as m
from .models import Constants, Player
from otree.common import safe_json
from otree.views.abstract import get_view_from_url
from otree.api import widgets
import random
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.template.response import TemplateResponse
from django.core.urlresolvers import reverse
from otree.models_concrete import (
    PageCompletion, CompletedSubsessionWaitPage,
    CompletedGroupWaitPage, PageTimeout, UndefinedFormModel,
    ParticipantLockModel, GlobalLockModel, ParticipantToPlayerLookup
)
import time
import channels
import json
from .consumers import get_group_name

class CustomWaitPage(WaitPage):
    template_name = 'customwp/CustomWaitPage.html'

    def is_displayed(self):
        if 'outofthegame' in self.player.participant.vars:
            return not self.player.participant.vars['outofthegame'] and self.extra_is_displayed()
        return self.extra_is_displayed()

    def extra_is_displayed(self):
        return True

class CustomPage(Page):
    timeout_seconds = 60

    def is_displayed(self):
        if 'outofthegame' in self.player.participant.vars:
            return not self.player.participant.vars['outofthegame'] and self.extra_is_displayed()
        return self.extra_is_displayed()

    def extra_is_displayed(self):
        return True

class StartWP(CustomWaitPage):
    group_by_arrival_time = True
    template_name = 'customwp/FirstWaitPage.html'

    def extra_is_displayed(self):
        return self.subsession.round_number == 1

    def vars_for_template(self):
        now = time.time()
        if not self.player.startwp_timer_set:
            self.player.startwp_timer_set = True
            self.player.startwp_time = time.time()
        time_left = self.player.startwp_time + Constants.startwp_timer - now
        return {'time_left': round(time_left)}

    def get_players_for_group(self, waiting_players):
        post_dict = self.request.POST.dict()
        endofgame = post_dict.get('endofgame')
        slowpokes = [p.participant for p in self.subsession.get_players()
                     if p.participant._index_in_pages
                     < self.index_in_pages]
        if len(slowpokes + waiting_players) < Constants.players_per_group:
            self.subsession.not_enough_players = True
        if endofgame:
            curplayer = [p for p in waiting_players if p.pk == int(endofgame)][0]
            curplayer.participant.vars['outofthegame'] = True
            return [curplayer]
        if len(waiting_players) == Constants.players_per_group:
            return waiting_players




page_sequence = [
    StartWP,

]

kelsey/templates/kelsey/Final.html
{% extends "global/PageExt.html" %}
{% load staticfiles otree_tags %}

{% block title %}

{% endblock %}

{% block inner_content %}
We will now start the {{Constants.first_half}} rounds of Part 1 of this experiment.

    {% next_button %}
{% endblock %}

kelsey/templates/kelsey/FinalInvestment.html
{% extends "global/PageExt.html" %}
{% load staticfiles otree_tags %}

{% block title %}
  {% include 'kelsey/title.html' %}: Final Investment
{% endblock %}

{% block inner_content %}
{% include 'kelsey/InfoBlock.html' %}

{{form}}
{% include 'kelsey/slider_wrapper.html' %}
    {% next_button %}

{% endblock %}

kelsey/templates/kelsey/InitialInvestment.html
{% extends "global/PageExt.html" %}
{% load staticfiles otree_tags %}

{% block title %}
  {% include 'kelsey/title.html' %}: Initial Investment
{% endblock %}

{% block inner_content %}
{% include 'kelsey/InfoBlock.html' %}

{% formfield player.first_decision with label=first_decision_label %}
{% include 'kelsey/slider_wrapper.html' %}
    {% next_button %}

{% endblock %}

kelsey/templates/kelsey/Instr3.html
{% extends "global/PageExt.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Part {{part_number}}: Instructions
{% endblock %}

{% block inner_content %}
  {% include 'kelsey/instruction_block1.html' %}
{% next_button %}

{% endblock %}

kelsey/templates/kelsey/Part2.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Part 2: Instructions
{% endblock %}

{% block content %}
<div><h3>Instructions for Part II here</h3></div>

    {% next_button %}
{% endblock %}

kelsey/templates/kelsey/QResults.html
{% extends "global/PageExt.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Part {{part_number}}: Answers to comprehension questions
{% endblock %}

{% block inner_content %}

{% include 'kelsey/InfoBlock.html' with initial_cost=Constants.q_parameters.initial_cost final_cost=Constants.q_parameters.final_cost high_payoff=Constants.q_parameters.high_payoff low_payoff=Constants.q_parameters.low_payoff   %}

<div class="well-lg well">
  Referring to the contract is shown above:
</div>




<table class="table table-hover table-striped table-bordered">
  <thead>
    <th>Question</th>
    <th>Your answer</th>
    <th>Correct answer</th>
    <th></th>

  </thead>
  <tbody>
  {% for p in data %}
    <tr>
      <th>{{p.0}}</th>
      <td>{{p.1}}</td>
      <td>{{p.2}}</td>
      <td>
        {% if p.3 %}
        <span class="glyphicon glyphicon-ok green" aria-hidden="true"></span>
        {% else %}
        <span class="glyphicon glyphicon-remove red" aria-hidden="true"></span>
        {% endif %}
      </td>
    </tr>
    {% endfor %}

  </tbody>
</table>

    {% next_button %}
{% endblock %}
{% block styles %}
  <style>

  </style>
{% endblock %}

kelsey/templates/kelsey/Results.html
{% extends "global/PageExt.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    {% include 'kelsey/title.html' %}: Results
{% endblock %}

{% block inner_content %}
{% include 'kelsey/InfoBlock.html' %}
{% include 'kelsey/result_block.html' with first_decision=player.first_decision %}

    {% next_button %}
    {% include 'kelsey/slider_wrapper.html' %}
{% endblock %}

{% block styles %}
<style>
.red{
    color: red;
}
.green{
    color: green;
}

.blue {
    color: blue;
}
.table > tbody > tr > td {
     vertical-align: middle;
}
</style>

{% endblock %}

kelsey/templates/kelsey/Separ.html
{% extends "global/PageExt.html" %}
{% load staticfiles otree_tags filka_tags %}

{% block title %}
    Begining of Part {{part_number}} of the study
{% endblock %}

{% block inner_content %}
    <h3>Now the study begins</h3>
<div class='row filkarow'>
   <div class="col-sm-12 col-md-12 col-lg-12">
<button id='show_example' class="btn btn-info btn-lg pull-left  " type='button'>Click to review the example</button>
<button class="otree-btn-next btn btn-primary btn-lg next-button otree-next-button pull-right filkabtn">Next</button>
</div>
</div>


    <div id="example" class='instructions'>
        {% include 'kelsey/inner_example.html' %}

</div>



{% endblock %}

{% block scripts %}
  <script>
    $('#show_example').click(function(){

      var $example = $('#example');
      $example.toggle();
      if ($example.is(':visible'))
      {$(this).text('Click to hide the example');}
      else   {$(this).text('Click to review the example');}
    });
  </script>
{% endblock %}

{% block styles %}
  <style media="screen">
    #example{
      margin-top:10px;
      margin-bottom: 10px;
      display:none;
    }
    .filkabtn{
      float:right:
    }
    .filkarow{margin-bottom: 10px;}
  </style>
{% endblock %}

kelsey/templates/kelsey/Survey.html
{% extends "global/PageExt.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    {% include 'kelsey/title.html' %}: Results
{% endblock %}

{% block inner_content %}
    <div>To help us with our research, please answer a few questions about yourself. You may leave any question blank
        that you do not wish to answer, but complete responses are very helpful for our research agenda.
    </div>
    {% formfield player.gender %}
    {% formfield player.nationality %}
    {% formfield player.nationality_other %}
    {% formfield player.race_ethnicity %}
    {% formfield player.race_ethnicity_other %}
    {% formfield player.major %}
    {% formfield player.year_in_college %}

    {% formfield player.stock_market_experience %}

    <div>
        Think back to the decisions you made in today’s study. Please answer these questions as honestly as possible.
    </div>
    {% formfield player.instructions %}
    {% formfield player.recommendations %}
    {% formfield player.random_contract %}
    {% formfield player.random_round %}
    {% formfield player.easiest %}
    {% formfield player.end_beginning %}
    {% formfield player.pleasant %}
    {% formfield player.thinking %}

    {% next_button %}

{% endblock %}

{% block styles %}

{% endblock %}

kelsey/templates/kelsey/example_first_decision.html
<div class="well-lg well">

    <label class="control-label"
           for="id_first_decision">Do you want to pay an initial investment cost of
        ${{ Constants.q_parameters.initial_cost }}{% if player.treatment == 'T2' %}and a final investment cost of $
            {{ Constants.q_parameters.final_cost }}{% endif %}?

    </label>

    <div class="controls  field-first_decision">
        <ul>
            <li><label for="id_first_decision_1"><input type="radio" disabled id="id_first_decision_1" value="True"
                                                        name="first_decision" required> Yes</label></li>

            <li><label for="id_first_decision_2"><input type="radio" disabled id="id_first_decision_2" value="False"
                                                        name="first_decision" required> No</label></li>
        </ul>

    </div>
</div>

kelsey/templates/kelsey/result_block.html
<table class="table table-hover table-striped">
  <thead><tr><th colspan=3>
    Your earnings in this round:
  </th></tr></thead>
  <tbody>
    {% if first_decision %}
<tr>
  <td>Initial investment: </td>
  <td>  <h5>
    <span class="glyphicon glyphicon-minus red" aria-hidden="true"></span>
    <span class="sr-only">Minus</span>
  </h5></td>
  <td>{{Constants.initial_cost}}</td>
</tr>

    {% if show_final_investment_block %}
<tr>

  <td>Investment payoff:</td>
  <td> <h5>
    <span class="glyphicon glyphicon-plus green" aria-hidden="true"></span>
    <span class="sr-only">Plus</span>
  </h5> </td>
  <td>{{investment_payoff|default:player.investment_payoff}}</td>
</tr>
<td>Final investment: </td>
<td>  <h5>
  <span class="glyphicon glyphicon-minus red" aria-hidden="true"></span>
  <span class="sr-only">Minus</span>
</h5></td>
<td>{{Constants.final_cost}}</td>
</tr>
{% endif %}
{% endif %}
<tr>
      {% if first_decision %}
  <th > </th>
  <th > <h5>
    =
  </h5> </th>
{% endif %}
  <th >{{payoff|default:player.payoff}}</th>
</tr>


</tbody>
</table>

kelsey/templates/kelsey/row_bootstrap.html
{% load floppyforms floppyforms_internals %}{% block row %}{% for field in fields %}
{% with classes=field.css_classes label=label|default:field.label help_text=help_text|default:field.help_text %}
{% block field %}<tr{% if classes %} class="{{ classes }}"{% endif %}>
    <th>{% block label %}{% if field|id %}<label for="{{ field|id }}">{% endif %}{{ label }}{% if label|last not in ".:!?" %}{% if not field.field.label_suffix|isnone %}{{ field.field.label_suffix }}{% else %}{{ form.label_suffix }}{% endif %}{% endif %}{% if field|id %}</label>{% endif %}{% endblock %}</th>

    {% for choice in field.field.choices %}
   <td>
     <div class="form-check">

       <label class="radio-inline" for="id_{{field.html_name}}_{{forloop.counter}}">
         <input type="radio" id="id_{{field.html_name}}_{{forloop.counter}}" value="{{choice.0}}"
          name="{{field.html_name}}" required="">{{choice.0}}
       </label>


</div>

   </td>


    {% endfor %}
    <td>
        {% block errors %}{% include "floppyforms/errors.html" with errors=field.errors %}{% endblock %}
        {% block widget %}

      {% endblock %}
        {% block help_text %}{% if help_text %}<br /><span class="helptext">{{ help_text }}</span>{% endif %}{% endblock %}
        {% block hidden_fields %}{% for field in hidden_fields %}{{ field.as_hidden }}{% endfor %}{% endblock %}
    </td>
</tr>{% endblock %}
{% endwith %}{% endfor %}{% endblock %}

kelsey/templates/kelsey/slider_wrapper.html
{% load staticfiles  %}
<div>
  <strong><h3 id='instr_toggler'>Show instructions:</h3></strong>
</div>
<label class="switch" >
  <input type="checkbox" id='instr_check'  >
  <div class="slider round"></div>
</label>
<div id="instructions" class='well well-lg instructions'>
  {% include 'kelsey/instruction_block1.html' %}
</div>

<link href="{% static 'css/slider.css' %}" rel="stylesheet">
<script src="{% static 'js/slider.js' %}"></script>

kelsey/templates/kelsey/title.html
    Part {{part_number}}: Round {{part_round_number}} of {{max_rounds}}